name: Android CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "Feature | **" ]

jobs:
  build:

    runs-on: emulator

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'android'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
